serverAddr = "x.x.x.x"
serverPort = 7000
transport.protocol = "kcp"
auth.method = "token"
auth.token = "YOUR TOKEN"            # 【需编辑】修改设置自己的token
loginFailExit=false


[[proxies]]
name = "my_socks5"                   # 名字可自行修改
type = "tcp"
remotePort = 6001                    # 可修改，这是你在外网使用代理时连接的端口
transport.useEncryption = true
transport.useCompression = true

# 定义插件类型为 socks5
[proxies.plugin]
type = "socks5"
username = "YOUR USERNAME"            # 【需编辑】设置连接代理时的用户名
password = "YOUR PASSWORD"            # 【需编辑】设置连接代理时的密码
